/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poliklinik.view;

import java.awt.Color;
import java.util.Date;  
import java.text.DateFormat;  
import java.text.SimpleDateFormat;
/**
 *
 * @author Gamal Robby
 */
public class Futama extends javax.swing.JFrame {

    /**
     * Creates new form Futama
     */
    public void validasilogin(){
        Session ses = new Session();
        lblNama.setText(ses.getNama_pegawai());
        if(ses.getPekerjaan().equalsIgnoreCase("dokter")){
            btnCMedik.setVisible(true);
            btnPenanganan.setVisible(true);
            btnPasien.setVisible(false);
            btnPegawai.setVisible(false);
            btnPembayaran.setVisible(false);
            btnObat.setVisible(false);
            btnCMedik.setBackground(new Color(39, 174, 96));
            bgDinamic.removeAll();
            bgDinamic.repaint();
            bgDinamic.revalidate();
            
            bgDinamic.add(pnlCMedik);
            bgDinamic.repaint();
            bgDinamic.revalidate();
        } else if (ses.getPekerjaan().equalsIgnoreCase("apoteker")){
            btnCMedik.setVisible(false);
            btnPenanganan.setVisible(false);
            btnPasien.setVisible(false);
            btnPegawai.setVisible(false);
            btnPembayaran.setVisible(true);
            btnObat.setVisible(true);
            btnPembayaran.setBackground(new Color(39, 174, 96));
            bgDinamic.removeAll();
            bgDinamic.repaint();
            bgDinamic.revalidate();
            
            bgDinamic.add(pnlPembayaran);
            bgDinamic.repaint();
            bgDinamic.revalidate();
        } else if (ses.getPekerjaan().equalsIgnoreCase("resepsionis")){
            btnCMedik.setVisible(false);
            btnPenanganan.setVisible(false);
            btnPasien.setVisible(true);
            btnPegawai.setVisible(false);
            btnPembayaran.setVisible(false);
            btnObat.setVisible(false);
            btnPasien.setBackground(new Color(39, 174, 96));
            bgDinamic.removeAll();
            bgDinamic.repaint();
            bgDinamic.revalidate();
            
            bgDinamic.add(pnlPasien);
            bgDinamic.repaint();
            bgDinamic.revalidate();
        } else if (ses.getPekerjaan().equalsIgnoreCase("admin")){
            btnCMedik.setVisible(false);
            btnPenanganan.setVisible(false);
            btnPasien.setVisible(true);
            btnPegawai.setVisible(true);
            btnPembayaran.setVisible(false);
            btnObat.setVisible(false);
            btnPasien.setBackground(new Color(39, 174, 96));
            bgDinamic.removeAll();
            bgDinamic.repaint();
            bgDinamic.revalidate();
            
            bgDinamic.add(pnlPasien);
            bgDinamic.repaint();
            bgDinamic.revalidate();
        }
    }
    private String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }  
    public void tampildata_catatanmedik()
    {
        Database db = new Database();
        TableCatatanMedik cMedik = new TableCatatanMedik();
        cMedik.setData(db.tampil_semua_catatanmedik());
        tblCatatanMedik.setModel(cMedik);
    }
    public Futama() {
        initComponents();
        validasilogin();
        lblTgl.setText("TGL : "+getTanggal());
        tampildata_catatanmedik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCMedik = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPenanganan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPasien = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPegawai = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPembayaran = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnObat = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lblTgl = new javax.swing.JLabel();
        bgDinamic = new javax.swing.JPanel();
        pnlCMedik = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCatatanMedik = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tampilCatatanMedik = new javax.swing.JTextArea();
        txtSearchCmedik = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        pnlPenanganan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        pnlPasien = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pnlPegawai = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pnlPembayaran = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pnlObat = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pnlPilihObat = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(13, 206, 112));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/poliklinik.png"))); // NOI18N
        pnlLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        pnlLeft.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        btnCMedik.setBackground(new java.awt.Color(13, 206, 112));
        btnCMedik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCMedik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCMedikMousePressed(evt);
            }
        });
        btnCMedik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/catatan.png"))); // NOI18N
        btnCMedik.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel5.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("C. MEDIK");
        btnCMedik.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnCMedik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 70));

        btnPenanganan.setBackground(new java.awt.Color(13, 206, 112));
        btnPenanganan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenanganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPenangananMousePressed(evt);
            }
        });
        btnPenanganan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/resep.png"))); // NOI18N
        btnPenanganan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel3.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PENANGANAN");
        btnPenanganan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnPenanganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 70));

        btnPasien.setBackground(new java.awt.Color(13, 206, 112));
        btnPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPasienMousePressed(evt);
            }
        });
        btnPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/pasien.png"))); // NOI18N
        btnPasien.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel9.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASIEN");
        btnPasien.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 70));

        btnPegawai.setBackground(new java.awt.Color(13, 206, 112));
        btnPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPegawaiMousePressed(evt);
            }
        });
        btnPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/pegawai.png"))); // NOI18N
        btnPegawai.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel7.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PEGAWAI");
        btnPegawai.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 70));

        btnPembayaran.setBackground(new java.awt.Color(13, 206, 112));
        btnPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPembayaranMousePressed(evt);
            }
        });
        btnPembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/bill.png"))); // NOI18N
        btnPembayaran.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel11.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PEMBAYARAN");
        btnPembayaran.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 70));

        btnObat.setBackground(new java.awt.Color(13, 206, 112));
        btnObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnObatMousePressed(evt);
            }
        });
        btnObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poliklinik/image/medicine.png"))); // NOI18N
        btnObat.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        jLabel13.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("OBAT");
        btnObat.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 70));

        pnlLeft.add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 70));

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 700));

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNama.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNama.setText("Nama");
        pnlTop.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 360, 30));

        btnLogout.setBackground(new java.awt.Color(13, 206, 112));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("LOGOUT");
        btnLogout.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        pnlTop.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 90, 70));

        lblTgl.setFont(new java.awt.Font("Clarendon BT", 0, 14)); // NOI18N
        lblTgl.setText("TGL");
        pnlTop.add(lblTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1010, 70));

        bgDinamic.setLayout(new java.awt.CardLayout());

        pnlCMedik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCatatanMedik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCatatanMedik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCatatanMedikMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCatatanMedik);

        pnlCMedik.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 78, 660, 520));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catatan Medik", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N

        tampilCatatanMedik.setEditable(false);
        tampilCatatanMedik.setColumns(20);
        tampilCatatanMedik.setLineWrap(true);
        tampilCatatanMedik.setRows(5);
        tampilCatatanMedik.setBorder(null);
        jScrollPane2.setViewportView(tampilCatatanMedik);

        pnlCMedik.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 280, 520));
        pnlCMedik.add(txtSearchCmedik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 30));

        jButton14.setBackground(new java.awt.Color(13, 206, 112));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Cari");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        pnlCMedik.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 30));

        jButton16.setBackground(new java.awt.Color(13, 206, 112));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Refresh");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        pnlCMedik.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 43, -1, 30));

        bgDinamic.add(pnlCMedik, "card2");

        pnlPenanganan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Obat / Tindakan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(13, 206, 112));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tambah Obat/Tindakan");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 70));

        pnlPenanganan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 270, 280));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Resep", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tindakan"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 220, 130));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Obat", "Jumlah Obat", "Aturan Pakai"
            }
        ));
        jScrollPane10.setViewportView(jTable9);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 550, 130));

        jLabel24.setText("NO PASIEN");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel25.setText("NO RESEP");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(13, 206, 112));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cetak");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        pnlPenanganan.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 910, 260));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukkan Nomor Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, 30));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, 30));

        jLabel14.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel14.setText("No Pasien");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel15.setText("No Resep");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(13, 206, 112));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pilih");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, -1));

        jButton4.setBackground(new java.awt.Color(13, 206, 112));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Batal");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        pnlPenanganan.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 310, 280));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Catatan Medik", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 170));

        jButton2.setBackground(new java.awt.Color(13, 206, 112));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jButton15.setBackground(new java.awt.Color(13, 206, 112));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Ubah");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setFocusPainted(false);
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, -1));

        pnlPenanganan.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 290, 280));

        bgDinamic.add(pnlPenanganan, "card3");

        jLabel20.setText("pasien");

        javax.swing.GroupLayout pnlPasienLayout = new javax.swing.GroupLayout(pnlPasien);
        pnlPasien.setLayout(pnlPasienLayout);
        pnlPasienLayout.setHorizontalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel20)
                .addContainerGap(658, Short.MAX_VALUE))
        );
        pnlPasienLayout.setVerticalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel20)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        bgDinamic.add(pnlPasien, "card4");

        jLabel21.setText("pegawai");

        javax.swing.GroupLayout pnlPegawaiLayout = new javax.swing.GroupLayout(pnlPegawai);
        pnlPegawai.setLayout(pnlPegawaiLayout);
        pnlPegawaiLayout.setHorizontalGroup(
            pnlPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPegawaiLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel21)
                .addContainerGap(721, Short.MAX_VALUE))
        );
        pnlPegawaiLayout.setVerticalGroup(
            pnlPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPegawaiLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(286, 286, 286))
        );

        bgDinamic.add(pnlPegawai, "card5");

        jLabel22.setText("pembayaran");

        javax.swing.GroupLayout pnlPembayaranLayout = new javax.swing.GroupLayout(pnlPembayaran);
        pnlPembayaran.setLayout(pnlPembayaranLayout);
        pnlPembayaranLayout.setHorizontalGroup(
            pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembayaranLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel22)
                .addContainerGap(653, Short.MAX_VALUE))
        );
        pnlPembayaranLayout.setVerticalGroup(
            pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembayaranLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel22)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        bgDinamic.add(pnlPembayaran, "card6");

        jLabel23.setText("onbat");

        javax.swing.GroupLayout pnlObatLayout = new javax.swing.GroupLayout(pnlObat);
        pnlObat.setLayout(pnlObatLayout);
        pnlObatLayout.setHorizontalGroup(
            pnlObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObatLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(jLabel23)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        pnlObatLayout.setVerticalGroup(
            pnlObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlObatLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(294, 294, 294))
        );

        bgDinamic.add(pnlObat, "card7");

        pnlPilihObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Obat/ Tindakan Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tindakan"
            }
        ));
        jScrollPane7.setViewportView(jTable6);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 340, 130));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Obat"
            }
        ));
        jScrollPane8.setViewportView(jTable7);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, 130));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 30));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, 30));

        jLabel16.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel16.setText("Cari Obat");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel17.setText("Cari Tindakan");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jButton6.setBackground(new java.awt.Color(13, 206, 112));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Pilih Obat");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, -1));

        jButton7.setBackground(new java.awt.Color(13, 206, 112));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Pilih Tindakan");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jButton10.setBackground(new java.awt.Color(13, 206, 112));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Cari");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 30));

        jButton11.setBackground(new java.awt.Color(13, 206, 112));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Cari");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 30));

        pnlPilihObat.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 260));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Aturan Pakai / Hapus Obat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Obat", "Jumlah Obat", "Aturan Pakai"
            }
        ));
        jScrollPane9.setViewportView(jTable8);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 550, 210));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 100, 30));

        jLabel18.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel18.setText("Jumlah Obat");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 220, 30));

        jLabel19.setFont(new java.awt.Font("Clarendon BT", 0, 12)); // NOI18N
        jLabel19.setText("Aturan Pakai");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jButton8.setBackground(new java.awt.Color(13, 206, 112));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Simpan");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 80, 30));

        jButton12.setBackground(new java.awt.Color(13, 206, 112));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Hapus");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 183, 80, 30));

        pnlPilihObat.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 340, 970, 270));

        jButton9.setBackground(new java.awt.Color(13, 206, 112));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("<= Kembali");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnlPilihObat.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 30));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tindakan Pada Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Clarendon BT", 0, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tindakan"
            }
        ));
        jScrollPane11.setViewportView(jTable10);

        jPanel7.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 170));

        jButton13.setBackground(new java.awt.Color(13, 206, 112));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Hapus");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 80, 30));

        pnlPilihObat.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 240, 260));

        bgDinamic.add(pnlPilihObat, "card8");

        getContentPane().add(bgDinamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 1010, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        login login = new login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(46, 213, 115));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(13,206,112));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnCMedikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMedikMousePressed
        // TODO add your handling code here:
        btnCMedik.setBackground(new Color(39, 174, 96));
        btnPenanganan.setBackground(new Color(13,206,112));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
            
        bgDinamic.add(pnlCMedik);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnCMedikMousePressed

    private void btnPenangananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenangananMousePressed
        // TODO add your handling code here:
        btnCMedik.setBackground(new Color(13,206,112));
        btnPenanganan.setBackground(new Color(39, 174, 96));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPenanganan);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnPenangananMousePressed

    private void btnPasienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPasienMousePressed
        // TODO add your handling code here:
        btnPasien.setBackground(new Color(39, 174, 96));
        btnPegawai.setBackground(new Color(13,206,112));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPasien);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnPasienMousePressed

    private void btnPegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPegawaiMousePressed
        // TODO add your handling code here:
        btnPasien.setBackground(new Color(13,206,112));
        btnPegawai.setBackground(new Color(39, 174, 96));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPegawai);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnPegawaiMousePressed

    private void btnPembayaranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembayaranMousePressed
        // TODO add your handling code here:
        btnPembayaran.setBackground(new Color(39, 174, 96));
        btnObat.setBackground(new Color(13,206,112));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPembayaran);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnPembayaranMousePressed

    private void btnObatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObatMousePressed
        // TODO add your handling code here:
        btnPembayaran.setBackground(new Color(13,206,112));
        btnObat.setBackground(new Color(39, 174, 96));
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlObat);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_btnObatMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPilihObat);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        bgDinamic.removeAll();
        bgDinamic.repaint();
        bgDinamic.revalidate();
 
        bgDinamic.add(pnlPenanganan);
        bgDinamic.repaint();
        bgDinamic.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tblCatatanMedikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatatanMedikMousePressed
        // TODO add your handling code here:
        int i = tblCatatanMedik.getSelectedRow();
        if (i>-1){
            tampilCatatanMedik.setText(tblCatatanMedik.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_tblCatatanMedikMousePressed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        TableCatatanMedik tabelMahasiswa = new TableCatatanMedik();
        String katakunci=txtSearchCmedik.getText();
        if (katakunci!=null){
            tabelMahasiswa.setData(db.cari_catatanmedik(katakunci));
            tabelMahasiswa.fireTableDataChanged();
            tblCatatanMedik.setModel(tabelMahasiswa);
        }
        txtSearchCmedik.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        tampildata_catatanmedik();
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Futama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgDinamic;
    private javax.swing.JPanel btnCMedik;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnObat;
    private javax.swing.JPanel btnPasien;
    private javax.swing.JPanel btnPegawai;
    private javax.swing.JPanel btnPembayaran;
    private javax.swing.JPanel btnPenanganan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JPanel pnlCMedik;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlObat;
    private javax.swing.JPanel pnlPasien;
    private javax.swing.JPanel pnlPegawai;
    private javax.swing.JPanel pnlPembayaran;
    private javax.swing.JPanel pnlPenanganan;
    private javax.swing.JPanel pnlPilihObat;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextArea tampilCatatanMedik;
    private javax.swing.JTable tblCatatanMedik;
    private javax.swing.JTextField txtSearchCmedik;
    // End of variables declaration//GEN-END:variables
}
